// user

export const LOGIN_START = '@user/LOGIN_START'
export const LOGIN_SUCCESS = '@user/LOGIN_SUCCESS'
export const LOGIN_ERROR = '@user/LOGIN_ERROR'

export const ME_START = '@user/ME_START'
export const ME_SUCCESS = '@user/ME_SUCCESS'
export const ME_ERROR = '@user/ME_ERROR'

export const SIGNUP_START = '@user/SIGNUP_START'
export const SIGNUP_SUCCESS = '@user/SIGNUP_SUCCESS'
export const SIGNUP_ERROR = '@user/SIGNUP_ERROR'

export const UPDATE_START = '@user/UPDATE_START'
export const UPDATE_SUCCESS = '@user/UPDATE_SUCCESS'
export const UPDATE_ERROR = '@user/UPDATE_ERROR'

export const RESET_PASSWORD_START = '@user/RESET_PASSWORD_START'
export const RESET_PASSWORD_SUCCESS = '@user/RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_ERROR = '@user/RESET_PASSWORD_ERROR'

export const NEW_PASSWORD_START = '@NEW_PASSWORD_START'
export const NEW_PASSWORD_SUCCESS = '@NEW_PASSWORD_SUCCESS'
export const NEW_PASSWORD_ERROR = '@NEW_PASSWORD_ERROR'

export const LOGOUT = '@user/LOGOUT'

// movies

export const GET_POPULAR_MOVIES_START = '@movie/GET_POPULAR_MOVIES_START'
export const GET_POPULAR_MOVIES_SUCCESS = '@movie/GET_POPULAR_MOVIES_SUCCESS'
export const GET_POPULAR_MOVIES_ERROR = '@movie/GET_POPULAR_MOVIES_ERROR'

export const GET_MOVIE_DETAILS_START = '@movie/GET_MOVIE_DETAILS_START'
export const GET_MOVIE_DETAILS_SUCCESS = '@movie/GET_MOVIE_DETAILS_SUCCESS'
export const GET_MOVIE_DETAILS_ERROR = '@movie/GET_MOVIE_DETAILS_ERROR'

export const MOVIE_SEARCH_START = '@movie/MOVIE_SEARCH_START'
export const MOVIE_SEARCH_SUCCESS = '@movie/MOVIE_SEARCH_SUCCESS'
export const MOVIE_SEARCH_ERROR = '@movie/MOVIE_SEARCH_ERROR'

// comments

export const PLACE_NEW_COMMENT_START = '@comment/PLACE_NEW_COMMENT_START'
export const PLACE_NEW_COMMENT_SUCCESS = '@comment/PLACE_NEW_COMMENT_SUCCESS'
export const PLACE_NEW_COMMENT_ERROR = '@comment/PLACE_NEW_COMMENT_ERROR'

export const GET_COMMENT_START = '@comment/GET_COMMENT_START'
export const GET_COMMENT_SUCCESS = '@comment/GET_COMMENT_SUCCESS'
export const GET_COMMENT_ERROR = '@comment/GET_COMMENT_ERROR'
